name: AssurHabitat CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installation de Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Installation des dépendances
        run: poetry install --no-interaction

      - name: Exécution de l'Évaluation
        run: |
          poetry run python -c "from src.evaluate import evaluer_pipeline; evaluer_pipeline('data/golden_dataset.csv', None, None)"

      - name: Archiver le rapport d'évaluation (Artifact CSV)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: evaluation-results-csv
          path: data/evaluation_results.csv

      - name: Validation du Build Docker
        run: |
          docker build -t assurhabitat-agents:latest .